version: '3.8'

services:
  mysql:
    container_name: demonestjs_dev_mysql
    build: mysqldatabase/dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nestjs
      MYSQL_PASSWORD: nestjs
      MYSQL_DATABASE: demonestjs
    ports:
      # Expose port 3307 on host machine in order to avoid collision with another MySQL instance running on host machine
      - '3307:3306'
    volumes:
      # Persist data between container invocation
      - 'dbdata:/var/lib/mysqldocker/data/dev'
    networks:
      netwdevnestjs:
        aliases:
          - database
  
  mongodb:
    image: mongo:4.4
    environment:
      - MONGODB_DATABASE="nest"
    ports:
      - 27017:27017
    networks:
      netwdevnestjs:
        aliases:
          - databasemongo

  app:
    container_name: demonestjs_dev_app
    image: node:15.14-alpine
    working_dir: /usr/src/app
    # Restart automatically docker on any file change
    command: sh -c "yarn && yarn run start:dev"
    volumes:
      # Mount a volume which will change each file changed locally
      - .:/usr/src/app
      # Mount an anonymous volume to keep node_modules from being overriden by local changes
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    networks:
      - netwdevnestjs
    depends_on:
      - mysql
      - mongodb

networks:
  netwdevnestjs:
volumes:
  dbdata:
